version: '3.4'

services:
  host:
    image: ${DOCKER_REGISTRY-}host
    build:
      context: .
      dockerfile: Host/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    environment:
        POSTGRES_DB: employees
        POSTGRES_USER: employees
        POSTGRES_PASSWORD: yourpassword
    ports:
        - "7777:5432"
